/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module frequency_divider_3 (
    input clk,
    input rst,
    output reg tick
  );
  
  
  
  reg [25:0] M_ctr_d, M_ctr_q = 1'h0;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    tick = M_ctr_q[25+0-:1];
    M_ctr_d = M_ctr_q + 1'h1;
    if (M_ctr_q[25+0-:1] == 1'h1) begin
      M_ctr_d[25+0-:1] = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
