/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module delay_step1_3 (
    input clk,
    input rst,
    output reg out
  );
  
  
  
  localparam SIZE = 5'h1d;
  
  reg [28:0] M_counter_d, M_counter_q = 28'ha0a1f00;
  
  reg M_flip_d, M_flip_q = 1'h0;
  
  always @* begin
    M_counter_d = M_counter_q;
    M_flip_d = M_flip_q;
    
    out = 1'h0;
    if (M_counter_q[28+0-:1]) begin
      out = 1'h1;
      M_flip_d = 1'h1;
    end
    if (M_flip_q) begin
      out = 1'h1;
    end
    M_counter_d = M_counter_q + 1'h1;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_flip_q <= 1'h0;
    end else begin
      M_flip_q <= M_flip_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 28'ha0a1f00;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
