/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_2 (
    input clk,
    input rst,
    output reg out
  );
  
  
  
  localparam SIZE = 4'he;
  
  reg [13:0] M_counter_d, M_counter_q = 12'hc78;
  
  always @* begin
    M_counter_d = M_counter_q;
    
    out = M_counter_q[13+0-:1];
    M_counter_d = M_counter_q + 1'h1;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 12'hc78;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
